config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'video/:id', to: 'pages#video', as: 'pages_video'
  get 'all-videos', to: 'pages#video_all', as: 'all_videos'
  devise_for :users,
              path: '',
              path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks'}


  resources :videos do
    resources :comments, only: [:create, :destroy]
  end
  resources :comments, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :video
  validates :user_id, presence: true
  validates :video_id, presence: true
  default_scope -> { order(updated_at: :desc)}
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:site_admin], multiple: false)                                      ##
  ############################################################################################


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :confirmable

  validates :fullname, presence: true, length: {maximum: 50}

  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first
    if user
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.fullname = auth.info.name
        user.image = auth.info.image
        user.uid = auth.uid
        user.provider = auth.provider
        # If you are using confirmable and the provider(s) you use validate emails,
        # uncomment the line below to skip the confirmation emails.
        user.skip_confirmation!
      end
    end
  end

  has_many :comments, dependent: :destroy

end

app/models/video.rb
class Video < ApplicationRecord
  validates :title, :description, :video_url, presence: true
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:fullname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  layout "dashboard"
  before_action :authenticate_user!
  access all: [:show], user:[:show, :destroy], site_admin: :all

  def index
    @comments = Comment.all
  end
  def create
   @video = Video.find(params[:video_id])
   @comment = @video.comments.build(comment_params)
   @comment.user = current_user
   if @comment.save
     flash[:success] = "Comment was created successfully"
     redirect_to pages_video_path(@video)
   else
     flash[:danger] = "Comment was not created"
     redirect_to :back
   end
 end

 def destroy
   @video = Video.find(params[:video_id])
   @comment = Comment.find(params[:id])
   @comment.destroy
    respond_to do |format|
     format.html { redirect_to comments_path }
   end
end

 private

 def comment_params
   params.require(:comment).permit(:description)
 end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @video = Video.last
    @videos = Video.last(3).reverse
  end

  def video_all
    @videos = Video.all
  end
  def video
    @video = Video.find(params[:id])
    @comment = Comment.new
    @comments = @video.comments
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
before_action :set_video, only: [:edit, :update, :show, :destroy]
layout "dashboard"
access all: [:show], site_admin: :all
def index
  @videos = Video.all
end
def new
  @video = Video.new
end
def create
  @video = Video.new(video_params)
  respond_to do |format|
    if @video.save
      format.html { redirect_to videos_path, notice: 'Your Video item is now live' }
    else
      format.html { render :new }
    end
  end
end

def edit

end

def update
  respond_to do |format|
    if @video.update(video_params)
          format.html { redirect_to videos_path, notice: 'Your Video is updated' }
    else
      format.html { render :edit }
    end
  end
end

def show
  @comment = Comment.new
  @comments = @video.comments
end

def destroy
  @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_path, notice: 'Video was successfully destroyed.' }
    end
end

private

  def set_video
    @video = Video.find(params[:id])
  end

  def video_params
    params.require(:video).permit(:title, :description, :video_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def remove_unwanted_words string
    bad_words = ["less than", "about"]

    bad_words.each do |bad|
      string.gsub!(bad + " ", '')
    end
    return string
  end
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/comments/_comment.html.erb
<div class="row">
  <div class="col-md-3">
    <section>
      <%= comment.user.fullname %>
      <p>
        <span class="quiet"><small>
                            <%= remove_unwanted_words time_ago_in_words(comment.created_at)%> ago </small></span>
      </p>
    </section>
  </div>
  <div class="col-md-12 well">
    <p><%= comment.description %></p>
     <% if current_user == comment.user || logged_in?(:site_admin) %>
    <%= link_to 'Delete', [comment.video, comment], method: :delete, data: { confirm: 'Are you sure?' }%>
  <% end%>
    <hr />


  </div>
</div>

app/views/comments/_comments.html.erb
<div>

<% comments.each do |comment| %>
  <%= render(partial: 'comments/comment', object: comment) %>
<% end %>
</div>

app/views/comments/index.html.erb
<div class="container-fluid">

  <div class="row">
    <div class="col-md-12">
      <table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>User</th>
      <th>Comment</th>
      <th>Actions</th>
    </tr>

  </thead>
  <tbody>
    <% @comments.each do |c| %>
    <tr>
      <th scope="row"><%= c.id %></th>
      <td><%= c.user.fullname %></td>
      <td><%= c.description %></td>
      <td><%= link_to 'Delete', [c.video, c], method: :delete, data: { confirm: 'Are you sure?' }%></td>
    </tr>
    <% end %>
</tbody>
</table>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>RedRadio</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '296310667503565',
          xfbml      : true,
          version    : 'v2.10'
        });
        FB.AppEvents.logPageView();
      };

      (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "//connect.facebook.net/en_US/sdk.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
    </script>
    <%= render 'shared/navbar' %>

    <div class="container-fluid main-body">

          <%= yield %>
    </div>

      <%= render 'shared/footer' %>


  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedRadio</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'dashboards', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/dashboard_nav' %>

    <div class="container">

          <%= yield %>
    </div>

      <%= render 'shared/footer' %>


  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <% if @videos.count != 0 %>
<section>
  <div class="row justify-content-md-center">
    <div class="col-md-8">
      <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src='https://www.youtube.com/embed/<%= @video.video_url %>' allowfullscreen></iframe>
      </div>
      </div>
      <div class="col-md-4">

          <h4 class="card-title"><%= link_to @video.title.truncate(50), pages_video_path(@video) %></h4>
          <p class="card-text"><%= simple_format truncate @video.description, length: 100 %> <%= link_to "Read More", pages_video_path(@video), class: 'btn btn-small btn-dark' %>  | <%= fa_icon "comment" %> <%= @video.comments.count %></p>

    </div>

</div>
<br />
<%end %>
      <div class="row">
        <% @videos.each do |v| %>
        <div class="col-md-4">
        <div class="card">
          <iframe class="card-img-top" src='https://www.youtube.com/embed/<%= v.video_url %>' frameborder='0' allowfullscreen></iframe>
          <div class="card-body">
            <h4 class="card-title"><%= link_to v.title.truncate(50), pages_video_path(v) %></h4>
            <p class="card-text"><%= simple_format truncate v.description, length: 150 %> <%= link_to "Read More", pages_video_path(v), class: 'btn btn-small btn-dark' %></p>
            </div>
             <div class="card-footer text-muted">
            <%= fa_icon "comment" %> <%= v.comments.count %>
            </div>

        </div>

        </div>
        <% end %>
      </div>

</section>
    </div>

app/views/pages/video.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-md-8">
        <h1><%= @video.title %></h1>
        <br />
        <iframe src='https://www.youtube.com/embed/<%= @video.video_url %>' frameborder='0' allowfullscreen class="iframe"></iframe>
        <%= simple_format @video.description %>

    </div>

  </div>
<hr />
<% if (user_signed_in?) %>
<div class="row justify-content-md-center">
  <div class="col-md-8">

    <%= form_for([@video, @comment], :html => {class: "form-horizontal",
                                              role: "form"}) do |f| %>
      <div class="form-group">
        <div class="form-group">
          <%= f.text_area :description, rows: 2, class: "form-control no-border",
                                    placeholder: "Enter Comment Here" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit "COMMENT", class: "btn btn-dark btn-lg" %>
        </div>
      </div>
    <% end %>
  </div>
</div>
    <% else %>
    <div class="row justify-content-md-center">
      <div class="col-md-8">
    <p>
      You must be signed in to leave a comment
    </p>
      </div>
    </div>

<% end %>
<hr />
  <div class="col-md-12">
    <h3><%= @video.comments.count%> <%= 'Comment'.pluralize(@video.comments.count) %></h3>
      <div id="messages">
        <%= render partial: 'comments/comments', object: @comments %>
      </div>
  </div>
</div>

app/views/pages/video_all.html.erb
<div class="container">
  <div class="row">
    <% @videos.each do |v| %>
    <div class="col-md-4">
    <div class="card">
      <iframe class="card-img-top" src='https://www.youtube.com/embed/<%= v.video_url %>' frameborder='0' allowfullscreen></iframe>
      <div class="card-body">
        <h4 class="card-title"><%= link_to v.title.truncate(50), pages_video_path(v) %></h4>
        <p class="card-text"><%= simple_format truncate v.description, length: 150 %></p>
        </div>
         <div class="card-footer text-muted">
        <%= link_to "Edit", edit_video_path(v) if logged_in?(:site_admin) %>
        </div>

    </div>
<br />
    </div>
    <br />
    <% end %>
  </div>
</div>

app/views/shared/_dashboard_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <%= link_to "redradio.live", root_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Videos", videos_path, class: "nav-link" %>
            
          </li>
          <li class="nav-item active">
            
            <%= link_to "Comments", comments_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </nav>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <span>&copy; Red Radio <%= Time.now.year %></span>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <%= link_to( image_tag('redradionew_white.png', width: '120px'), root_path, class:'navbar-brand')  %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Videos", all_videos_path, class:"nav-link" %>
      </li>
      
    </ul>
    <ul class="navbar-nav my-2 my-lg-0">
      <% if (!user_signed_in?) %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: 'nav-link mr-auto' %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: 'nav-link mr-auto' %>
        </li>
      <% else %>
        <li class="nav-item dropdown">
             <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_user.fullname %></a>
             <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown01">
               <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
               <%= link_to "Dashboard", videos_path, class: "dropdown-item" if logged_in?(:site_admin) %>
               <%= link_to "Log Out", destroy_user_session_path, class: "dropdown-item", method: :delete %>
             </div>
        </li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
<% if @video.errors.any? %>
  <% @video.errors.full_messages.each do |error| %>
    <%= alert_generator error %>
  <% end %>
<% end %>

      <div class="form-group">
        <%= f.label :video_url %>
        <%= f.text_field :video_url, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control', rows: 15, placeholder: 'Content' %>
      </div>

          <div class="form-group">
            <%= f.submit "Save Video", class: "btn btn-success btn-block" %>
          </div>

            <div class="form-group">
              <%= link_to "Cancel", videos_path, class: "btn btn-danger btn-block" %>
            </div>
<% end %>

app/views/videos/_video.html.erb
<div class="col-md-4">
  <div class="card">
    <iframe class="card-img-top" src='https://www.youtube.com/embed/<%= video.video_url %>' frameborder='0' allowfullscreen></iframe>
    <div class="card-body">
      <h4 class="card-title"><%= link_to video.title.truncate(50), video_path(video) %></h4>
      <p class="card-text"><%= simple_format truncate video.description, length: 150 %></p>
      <hr />
      <%= link_to "Edit", edit_video_path(video) if logged_in?(:site_admin) %> |
      <%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
</div>

app/views/videos/edit.html.erb
<div class="container">
  <h1>Edit Video</h1>

  <%= render 'form', video_item: @video %>
</div>

app/views/videos/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-4">
    <%= link_to "Create Video", new_video_path, class: 'btn btn-info' %>
  </div>
</div>
<br />
  <div class="row">
      <%= render @videos %>
    </div>
  </div>
</div>
</div>

app/views/videos/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1>Create A new Video</h1>

      <%= render 'form', video_item: @video %>
    </div>
  </div>
</div>

app/views/videos/show.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-md-8">
        <h1><%= @video.title %></h1>
        <br />
        <iframe src='https://www.youtube.com/embed/<%= @video.video_url %>' frameborder='0' allowfullscreen class="iframe"></iframe>
        <%= simple_format @video.description %>
    </div>
  </div>
</div>
<% if (user_signed_in?) %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h3>Comments: </h3>
    <hr />
    <%= form_for([@video, @comment], :html => {class: "form-horizontal",
                                              role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :description, "Comment" %>
        </div>
        <div class="col-md-8">
          <%= f.text_area :description, rows: 8, class: "form-control",
                                    placeholder: "Enter Comment Here" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit "Submit Comment",
                            class: "btn btn-primary btn-lg btn-xlarge" %>
        </div>
      </div>
    <% end %>
    <hr />
  </div>
</div>
<% end %>
<% if @video.comments != 0 %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h3>Prior Comments: </h3>
      <div id="messages">
        <%= render partial: 'comments/comments', object: @comments %>
      </div>
  </div>
</div>
<% else %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h3>No Comments Yet!</h3>
  </div>
</div>
<% end %>
</div>